cloud/package.json, cloud/server/collections/Licenses.ts, cloud/server/test/Seeder.ts
=> Dummylicenses

src/app/app.module.ts, src/app/app.routes.ts, src/app/cloud/cloud-container/container/sidebar.html, src/app/cloud/pages/admin-area/manage-users.ts, src/app/cloud/pages/admin-area/manage-users/grid.html, src/app/cloud/pages/admin-area/manage-users/grid.ts, src/app/cloud/pages/admin-area/manage-users/manage-users.service.ts
=> manage users

cloud/server/collections/Products.ts, cloud/server/test/Seeder.ts, src/app/app.module.ts, src/app/app.routes.ts, src/app/cloud/pages/admin-area/manage-products/create-version.html, src/app/cloud/pages/admin-area/manage-products/create-version.ts, src/app/cloud/pages/admin-area/manage-products/create.html, src/app/cloud/pages/admin-area/manage-products/edit.html, src/app/cloud/pages/admin-area/manage-products/edit.ts, src/app/cloud/pages/admin-area/manage-products/manage-products.service.ts
=> edit product interface

src/app/cloud/pages/admin-area/manage-products/grid.ts, src/app/cloud/pages/admin-area/manage-products/manage-products.service.ts
=> remove product

cloud/server/methods/auth/email-config.ts, cloud/server/methods/user/create_user.ts, package.json, src/app/app.routes.ts, src/app/cloud/pages/admin-area/manage-users/form.ts, src/app/cloud/pages/auth/signin.html
=> enroll account

cloud/server/methods/user/send_verification.ts, src/app/app.routes.ts, src/app/cloud/pages/auth/verify.html, src/app/cloud/pages/auth/verify.ts, src/app/cloud/services/ddp/auth.service.ts, src/app/cloud/services/router-guard/authenticate.ts
=> verify email

src/app/modules/+pos/modules/+configurations/view/default/general.component.html, src/styles/pos/_config.scss, src/styles/pos/_home.scss, src/styles/pos/_mixins.scss
=> fix on tablet screen

src/app/modules/+pos/core/framework/store/Helper/StoreHelper.ts, src/app/modules/+pos/view/default/sales/checkout/popup/customer-detail/list-address.component.ts
refactor get store ( viết luôn vào core vì không ảnh hưởng đến các function khác )
fix xrt 1373 Order/Cart - Disallow negative shipment
=> merge request

src/app/modules/+pos/view/R/sales/checkout/cart/customer.service.ts, src/app/modules/+pos/view/default/sales/checkout/cart/items/item.component.ts, src/app/modules/+pos/view/default/sales/checkout/cart/totals.component.html, src/app/modules/+pos/view/default/sales/checkout/cart/totals.component.ts, src/app/modules/+pos/view/default/sales/checkout/popup/customer-detail/list-address.component.ts, src/app/modules/+pos/view/default/sales/orders/detail.component.html
=> Fix XRT-1476, XRT-1359, XRT-1520, XRT-1470, XRT-1312

src/app/modules/+pos/view/default/sales/checkout/actions-bar.component.html, src/app/modules/+pos/view/default/sales/checkout/actions-bar.component.ts
Click on "Send to Customer's Wish list"
Click on "Save Current Cart".
note: save note must work in exchange process.
=> Click on "Add Note" and try to edit the note.

src/app/modules/+pos/core/framework/store/Helper/StoreHelper.ts, src/app/modules/+pos/view/default/sales/checkout/actions-bar.component.ts
=> remove check your options when select outlet store view

src/app/modules/+pos/R/sync/sync.service.ts, src/app/modules/+pos/core/framework/General/DateTime/Timezone.ts
=> Update retail time

src/app/modules/+pos/view/default/sales/checkout/cart/customers.component.ts, src/app/modules/+pos/view/default/sales/checkout/cart/items/item.component.html, src/app/modules/+pos/view/default/sales/checkout/cart/items/item.component.ts, src/app/modules/+pos/view/default/sales/checkout/cart/totals.component.html, src/app/modules/+pos/view/default/sales/checkout/cart/totals.component.ts, src/app/modules/+pos/view/default/sales/checkout/grand-total.component.ts, src/app/modules/+pos/view/default/sales/checkout/popup/customer-detail/billing.component.html, src/app/modules/+pos/view/default/sales/checkout/popup/customer-detail/billing.component.ts, src/app/modules/+pos/view/default/sales/checkout/popup/customer-detail/list-address.component.ts, src/app/modules/+pos/view/default/sales/checkout/top-bar.component.ts, src/app/modules/+pos/view/default/sales/menu-left.component.html, src/app/modules/+pos/view/default/sales/menu-left.component.ts, src/app/modules/+pos/view/default/sales/shifts/detail.component.ts, src/app/modules/+pos/view/default/sales/shifts/list.component.ts
=> Feature Permission

src/app/modules/+pos/view/R/sales/receipts/receipt.actions.ts, src/app/modules/+pos/view/R/sales/receipts/receipt.effects.ts, src/app/modules/+pos/view/R/sales/receipts/receipt.reducer.ts, src/app/modules/+pos/view/R/sales/receipts/receipt.service.ts, src/app/modules/+pos/view/R/sales/receipts/receipt.state.ts, src/app/modules/+pos/view/default/sales/checkout/step/complete.component.ts, src/app/modules/+pos/view/default/sales/orders/detail.component.ts
=> Feature Send Email Receipt

src/app/modules/+pos/core/framework/General/DateTime/Timezone.ts, src/app/modules/+pos/view/R/sales/checkout/step/step.effects.ts
=> refactor time

src/app/modules/+pos/view/default/sales/checkout/step.component.html
=> Fix XRT-1562 Email Receipt

src/app/modules/+pos/view/default/sales/checkout/popup/product-detail.component.html, src/app/modules/+pos/view/default/sales/checkout/step/payment/cash.component.ts, src/app/modules/+pos/view/default/sales/checkout/step/payment/credit-card.component.ts, src/app/modules/+pos/view/default/sales/checkout/step/payment/tyro.component.ts
Fix error when type amount have dot XRT-1660
=> Add Pipe for qty in product detail XRT- 1397

src/app/modules/+pos/view/default/sales/checkout/popup/product-detail/bundle-options.component.ts
=> validate after select option and after all bundle option updated

src/app/modules/+pos/R/config/config.reducer.ts, src/app/modules/+pos/R/config/config.state.ts, src/app/modules/+pos/view/default/sales/checkout/popup/customer-detail/form.component.ts, src/app/modules/pos-element/components/select2.component.ts
=> Feature New Customer Default Country and validate require country/region

src/app/modules/+pos/view/default/sales/shifts/detail.component.html, src/app/modules/+pos/view/default/sales/shifts/report.component.html
=> fix display tax in shift for the connector do not update

src/app/modules/+pos/view/default/sales/checkout/popup/product-detail/bundle-options.component.ts
=> Remove validate if bundle option not require

src/app/modules/+pos/modules/+configurations/view/default/pos/product-category/settings.component.ts
=> change texts (XRT-1601)

src/app/modules/+pos/view/default/sales/menu-left.component.ts
=> update display outlet/register follow by design

src/app/modules/+pos/view/default/sales/orders/detail.component.html
=> Saving wrong customer telephone in order details

src/app/modules/+pos/view/R/sales/checkout/cart/customer.service.ts
=> Fix search customer

src/app/modules/+pos/view/default/sales/checkout/popup/customer-detail/form.component.ts
=> Fix XRT-1748 Is not update country of address customer on CPOS

src/app/modules/+pos/R/quote/quote.reducer.ts
=> nFix xrt 1781

src/styles/pos/_global.scss
=> Fix bug autocomplete

src/app/modules/+pos/modules/+configurations/view/default/pos/receipt/template.component.html, src/app/modules/+pos/view/default/sales/checkout/list.component.html
=> fix xrt 1894

src/app/modules/+pos/R/quote/quote.effects.ts
=> fix xrt 1882 sai kiểu khi compare multiple option

src/styles/pos/_main.scss
=> fix issue XRT 58

src/app/modules/+pos/view/default/sales/checkout/actions-bar.component.html, src/app/modules/+pos/view/default/sales/checkout/actions-bar.component.ts, src/app/modules/+pos/view/default/sales/checkout/cart/items/item.component.html, src/app/modules/+pos/view/default/sales/checkout/cart/items/item.component.ts
=> fix issue XRT 88

src/app/modules/pos-element/components/select.component.html
=> fix issue XRT 842

src/app/R/account/account.service.ts, src/app/services/app-helper.ts, src/app/services/index.ts, src/app/services/request.ts
=> Check API version compatiable

src/app/modules/+pos/core/local/warehouse/Helper/WarehouseHelper.ts, src/app/modules/+pos/modules/+configurations/R/outlets/outlet.service.ts, src/app/modules/+pos/modules/+configurations/view/default/pos/outlet-register/grid.component.html, src/app/modules/+pos/modules/+configurations/view/default/pos/outlet-register/grid.component.ts, src/app/modules/+pos/modules/+configurations/view/default/pos/outlet-register/grid/table.component.html, src/app/modules/+pos/modules/+configurations/view/default/pos/outlet-register/grid/table.component.ts
=> Show warehouse name in Outlet listing

src/app/modules/+pos/view/default/sales/receipt.component.html
=> fix issue XRT 1640

src/app/modules/+pos/R/quote/quote.effects.ts
=> fix issue XRT 504
